#camunda:
#  bpm:
#    database.schema-update: false
#    job-execution:
#      deployment-aware: true
#    admin-user:
#      id: demo
#      password: demo
#      firstName: Demo
#    filter:
#      create: All tasks
#
#
#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/camunda-training;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password: